Add black to neurom, format everything, and add to lint
BlueBrain/NeuroM pull request #1042
Opened 2022-05-24 15:03 UTC by eleftherioszisis

2022-05-24 16:09 UTC, adrien-berchet commented on tox.ini
>  basepython=python3.7
You could add `skip_install = true` in this section.

2022-05-25 07:27 UTC, mgeplf commented
GIthub turned on handling of `.git-blame-ignore-revs` (https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/), so we'll add the commit there, once it has a stable hash

2022-05-25 07:42 UTC, mgeplf approved these changes

2022-05-25 07:53 UTC, mgeplf requested changes
Let's allow single quotes w/ `--skip-string-normalization`, and rerun the format.

2022-05-30 06:34 UTC, eleftherioszisis commented
@mgeplf is it good now?

2022-05-30 06:38 UTC, mgeplf approved these changes

2022-06-07 07:11 UTC, merged